services:
  postgres:
    image: postgres:latest
    container_name: cerebra-database-postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
    ports:
      - "5432:5432"